# workflow to show how to develop workflows in branches
name: Develop in a banch
on: [pull_request, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: |
           echo "::debug::This is a debug message."
           echo "::notice::This is a notice message."
           echo "::warning::This is a warning message."
           echo "::error::This is an error message."
      - uses: actions/checkout@v5
      - uses: devops-actions/actionlint@v0.1.9